## **Tensor Basics**

Similar to Numpy, In pytorch we use tensors(can be 1-D, 2-D or 3-D).


In [1]:
import torch

In [2]:
#crearting an empty tensot
x=torch.empty(3)
print(x)

tensor([3.6022e-12, 7.1223e+28, 3.0958e-18])


In [3]:
# 2-D tensor
x_2=torch.empty(3,2)
print(x_2)

tensor([[6.7295e-38, 0.0000e+00],
        [6.7296e-38, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]])


In [4]:
#creating tensor with Random values
x_r=torch.rand(3,2)
print(x_r)

tensor([[0.6084, 0.1118],
        [0.6875, 0.3470],
        [0.1654, 0.2607]])


In [5]:
#creating tensor with ones
x_1=torch.ones(2,2)
print(x_1)

tensor([[1., 1.],
        [1., 1.]])


In [7]:
#creating with a certain data type
#the default type of troch is float32

x_d=torch.rand(2,2 , dtype=torch.double)
print(x_d)

tensor([[0.5970, 0.3309],
        [0.4699, 0.6507]], dtype=torch.float64)


In [9]:
#to check the size of the tensor
print(x_d.size())
print(x_d.shape)

torch.Size([2, 2])
torch.Size([2, 2])


In [10]:
#constructing a pytorch tensor from a python list
x_l = torch.tensor([1,2,3,67,98,900])
print(x_l)

tensor([  1,   2,   3,  67,  98, 900])


### **Operarion on the Tensors**

In [13]:
#operation on the tensors
x=torch.rand(4,4)
y=torch.rand(4,4)
print(x)
print(y)

tensor([[0.1502, 0.6757, 0.2344, 0.3842],
        [0.4933, 0.3161, 0.8865, 0.3239],
        [0.1537, 0.6337, 0.5949, 0.1984],
        [0.6676, 0.0141, 0.4993, 0.8975]])
tensor([[0.0355, 0.9684, 0.1909, 0.2049],
        [0.7968, 0.1251, 0.3922, 0.1033],
        [0.7408, 0.9357, 0.9725, 0.4295],
        [0.9344, 0.5325, 0.8902, 0.5777]])


In [14]:
#element -wise addition
z=x+y
print(z)
z1=torch.add(x,y)
print(z)
z==z1

tensor([[0.1857, 1.6440, 0.4253, 0.5892],
        [1.2901, 0.4413, 1.2787, 0.4272],
        [0.8945, 1.5694, 1.5674, 0.6279],
        [1.6020, 0.5465, 1.3894, 1.4752]])
tensor([[0.1857, 1.6440, 0.4253, 0.5892],
        [1.2901, 0.4413, 1.2787, 0.4272],
        [0.8945, 1.5694, 1.5674, 0.6279],
        [1.6020, 0.5465, 1.3894, 1.4752]])


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [16]:
#Changes only occur in tensor 'y'
y.add_(x)
print(y)

tensor([[0.3359, 2.3197, 0.6598, 0.9734],
        [1.7834, 0.7574, 2.1651, 0.7511],
        [1.0483, 2.2031, 2.1623, 0.8263],
        [2.2696, 0.5606, 1.8887, 2.3728]])


In [ ]:
#all operation will be the same like 'addition', 'substraction', 'multiplication','division'

### **Slicing operations are smiliar to the  numpy**

In [19]:
print(x)
print(x[1,:])
print(x[:,1])

tensor([[0.1502, 0.6757, 0.2344, 0.3842],
        [0.4933, 0.3161, 0.8865, 0.3239],
        [0.1537, 0.6337, 0.5949, 0.1984],
        [0.6676, 0.0141, 0.4993, 0.8975]])
tensor([0.4933, 0.3161, 0.8865, 0.3239])
tensor([0.6757, 0.3161, 0.6337, 0.0141])


In [21]:
#if you know that you only have one element in tensro, you can use item() method
print(x[1,1].item())

0.3161376118659973


### **Reshaping the tensors**

In [22]:
re=torch.rand(4,4)
print(re)

tensor([[0.1401, 0.5820, 0.4492, 0.9878],
        [0.0866, 0.0678, 0.2314, 0.3395],
        [0.1150, 0.2850, 0.0933, 0.7240],
        [0.6974, 0.9427, 0.2085, 0.8725]])


In [24]:
re1=x.view(-1,8)
print(re1.size())
print(re.size())

torch.Size([2, 8])
torch.Size([4, 4])


In [25]:
#converting numpy array into tensors and vice-versa
import numpy as np

In [26]:
a = torch.ones(5)
print(a)
b=a.numpy()
print(b)
print(type(b))


tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


If the numpy is on cpu then both objects will share the same location. So it's advisable to create tensors on 'GPU'.

Change in one object leads to change in other object.

In [28]:
a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


# How to avoid?

In [30]:
t=torch.from_numpy(b)
print(t)

tensor([3., 3., 3., 3., 3.])


In [32]:
b +=1
print(b)
print(t)

[4. 4. 4. 4. 4.]
tensor([4., 4., 4., 4., 4.])


In [44]:
# to avoid
if torch.cuda.is_available():
  device =  torch.device('cuda')
  t_gpu=torch.rand(3,3,device=device)
  y=torch.rand(3,3)
  y=y.to(device)

`requires_grad=True`
Add this if you want to calucalate the Gradients of tensot in the future